name: pm_android
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:

  firebase_core: ^2.13.0
  get: ^4.6.5
  firebase_database: ^10.2.1
  google_fonts: ^4.0.5
  sleek_circular_slider : ^2.0.1
  internet_connectivity_checker: ^1.0.0


  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
