// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_iocUNeJIz-6De7wwlqK_XhkyXtUh9jY',
    appId: '1:864742088604:android:49ea2d7b3f6926573c7259',
    messagingSenderId: '864742088604',
    projectId: 'progress-monitor-f9fae',
    databaseURL: 'https://progress-monitor-f9fae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'progress-monitor-f9fae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGYcOdqhz7LSfZIRaAn1YMmrKcC79Jxuk',
    appId: '1:864742088604:ios:f6a9d8006463ba283c7259',
    messagingSenderId: '864742088604',
    projectId: 'progress-monitor-f9fae',
    databaseURL: 'https://progress-monitor-f9fae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'progress-monitor-f9fae.appspot.com',
    iosClientId: '864742088604-una7shkb6q9kmk6tf3ns0rdi50mgf75a.apps.googleusercontent.com',
    iosBundleId: 'com.example.pmAndroid',
  );
}
